# Generated by Django 4.1.3 on 2022-11-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='username',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
