# Generated by Django 4.1.3 on 2022-11-16 08:00

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_extenduser_email_alter_extenduser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='name yet to be updated', max_length=150),
        ),
    ]
