# Generated by Django 4.1.3 on 2022-11-10 13:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_options_alter_extenduser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/profilepic/'), upload_to=''),
        ),
    ]
