# Generated by Django 4.1.3 on 2022-11-11 05:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_extenduser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/profilepic'), upload_to=''),
        ),
    ]
