# Generated by Django 4.1.3 on 2022-11-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_name_address_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
