# Generated by Django 4.1.3 on 2022-11-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/no_image.png', upload_to='media/profile_pics'),
        ),
    ]
