# Generated by Django 4.1.3 on 2022-11-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_extenduser_email_alter_extenduser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], default='home', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
