# Generated by Django 4.1.3 on 2022-11-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_address_address_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Home', 'home'), ('Office', 'office'), ('Other', 'other')], default='home', max_length=20),
        ),
    ]
