# Generated by Django 4.1.3 on 2022-11-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Home', 'home'), ('Office', 'office'), ('Other', 'other')], default='Home', max_length=20),
        ),
    ]
