# Generated by Django 4.1.3 on 2022-11-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_address_address_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Area',
            new_name='Sector',
        ),
    ]
