# Generated by Django 4.1.3 on 2022-11-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_area_address_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Sector',
            new_name='sector',
        ),
    ]
