# Generated by Django 4.1.3 on 2022-11-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_sector_address_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Home', 'home'), ('Office', 'office'), ('Other', 'other')], default='Home', max_length=20),
        ),
    ]
