# Generated by Django 4.1.3 on 2022-11-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title of product', max_length=50)),
                ('description', models.CharField(default='description of product', max_length=500)),
                ('price', models.CharField(default=100, max_length=10)),
                ('image', models.ImageField(null=True, upload_to='cloth_images')),
            ],
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title of product', max_length=50)),
                ('description', models.CharField(default='description of product', max_length=500)),
                ('price', models.CharField(default=100, max_length=10)),
                ('image', models.ImageField(null=True, upload_to='cloth_images')),
            ],
        ),
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title of product', max_length=50)),
                ('description', models.CharField(default='description of product', max_length=500)),
                ('price', models.CharField(default=100, max_length=10)),
                ('image', models.ImageField(null=True, upload_to='cloth_images')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title of product', max_length=50)),
                ('description', models.CharField(default='description of product', max_length=500)),
                ('price', models.CharField(default=100, max_length=10)),
                ('image', models.ImageField(null=True, upload_to='cloth_images')),
            ],
        ),
    ]
