# Generated by Django 4.1.3 on 2022-11-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Electronic',
            new_name='Electronics',
        ),
        migrations.AlterModelOptions(
            name='electronics',
            options={'verbose_name': 'Electronics'},
        ),
        migrations.AlterModelOptions(
            name='fashion',
            options={'verbose_name': 'Fashion'},
        ),
        migrations.AlterModelOptions(
            name='gadgets',
            options={'verbose_name': 'Gadgets'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home'},
        ),
    ]
