# Generated by Django 4.1.3 on 2022-11-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_electronic_electronics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electronics',
            options={'verbose_name': 'Electronic'},
        ),
        migrations.AlterModelOptions(
            name='gadgets',
            options={'verbose_name': 'Gadget'},
        ),
    ]
