# Generated by Django 4.1.3 on 2022-11-17 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_electronics_options_alter_gadgets_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='image',
            field=models.ImageField(null=True, upload_to='electronic_images'),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='image',
            field=models.ImageField(null=True, upload_to='fashion_images'),
        ),
        migrations.AlterField(
            model_name='gadgets',
            name='image',
            field=models.ImageField(null=True, upload_to='gadgets_images'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(null=True, upload_to='home_images'),
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.electronics')),
                ('fashion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.fashion')),
                ('gadgets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.gadgets')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.home')),
                ('user_collection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection',
            },
        ),
    ]
