# Generated by Django 4.1.3 on 2022-11-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_electronics_image_alter_fashion_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.electronics')),
                ('fashion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.fashion')),
                ('gadgets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.gadgets')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.home')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
        migrations.DeleteModel(
            name='Collections',
        ),
    ]
