# Generated by Django 4.1.3 on 2022-11-18 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_delete_collections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electronics',
            options={'verbose_name': 'electronics'},
        ),
        migrations.AlterModelOptions(
            name='fashion',
            options={'verbose_name': 'fashion'},
        ),
        migrations.AlterModelOptions(
            name='gadgets',
            options={'verbose_name': 'gadgets'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'home'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Products'},
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='description',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='image',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='price',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='title',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='price',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='title',
        ),
        migrations.RemoveField(
            model_name='gadgets',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gadgets',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gadgets',
            name='price',
        ),
        migrations.RemoveField(
            model_name='gadgets',
            name='title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='price',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title',
        ),
        migrations.RemoveField(
            model_name='products',
            name='electronics',
        ),
        migrations.RemoveField(
            model_name='products',
            name='fashion',
        ),
        migrations.RemoveField(
            model_name='products',
            name='gadgets',
        ),
        migrations.RemoveField(
            model_name='products',
            name='home',
        ),
        migrations.AddField(
            model_name='electronics',
            name='electronics_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AddField(
            model_name='fashion',
            name='fashion_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AddField(
            model_name='gadgets',
            name='gadgets_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AddField(
            model_name='home',
            name='home_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='description of product', max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='home_images'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(default=100, max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(default='title of product', max_length=50),
        ),
    ]
