# Generated by Django 4.1.3 on 2022-11-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_electronics_options_alter_fashion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('Fashion', 'fashion'), ('Gadgets', 'gadgets'), ('Home', 'home'), ('Electronics', 'electronics')], max_length=20, null=True),
        ),
    ]
