# Generated by Django 4.1.3 on 2022-11-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electronics',
            options={'verbose_name': 'Electronic'},
        ),
        migrations.AlterModelOptions(
            name='gadgets',
            options={'verbose_name': 'Gadget'},
        ),
    ]
