# Generated by Django 4.1.3 on 2022-11-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_collections_user_alter_collections_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collections',
            old_name='user',
            new_name='added_by',
        ),
        migrations.AddField(
            model_name='collections',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
